# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: 156615540+bob2006najj@users.noreply.github.com
author_name: ibrahim najjar
cloud_provider: none
preset_name: production
project_name: Algorand-Food-Pass

